name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
      VITE_APP_AUTH_DOMAIN: ${{ secrets.VITE_APP_AUTH_DOMAIN }}
      VITE_APP_DATABASE_URL: ${{ secrets.VITE_APP_DATABASE_URL }}
      VITE_APP_PROJECT_ID: ${{ secrets.VITE_APP_PROJECT_ID }}
      VITE_APP_STORAGE_BUCKET: ${{ secrets.VITE_APP_STORAGE_BUCKET }}
      VITE_APP_MESSAGING_SENDER_ID: ${{ secrets.VITE_APP_MESSAGING_SENDER_ID }}
      VITE_APP_APP_ID: ${{ secrets.VITE_APP_APP_ID }}
      VITE_APP_MEASUREMENT_ID: ${{ secrets.VITE_APP_MEASUREMENT_ID }}
      VITE_APP_EMAIL_SERVICE_ID: ${{ secrets.VITE_APP_EMAIL_SERVICE_ID }}
      VITE_APP_EMAIL_TEMPLATE_ID: ${{ secrets.VITE_APP_EMAIL_TEMPLATE_ID }}
      VITE_APP_EMAIL_USER_ID: ${{ secrets.VITE_APP_EMAIL_USER_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_PORTFOLIO_63ACB }}'
          channelId: live
          projectId: my-portfolio-63acb